name: Update Profile README

on:
  schedule:
    - cron: "0 */6 * * *"  # Every 6 hours
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Fetch commit history
        uses: jamesgeorge007/github-activity-readme@v0.2.0
        with:
          COMMIT_MSG: "Updated README with latest GitHub activity"
          MAX_LINES: 15
          REPOSITORY: MUHSIN-M-P/MUHSIN-M-P
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
